package com.rncoding.testvineshield.core.domain.disease_risk

enum class DiseaseRiskEvent {
    ASCOSPORE_RELEASE_CONDITIONS,
    ASCOSPORE_INFECTION_CONDITIONS,

    CONIDIAL_RISK_INITIATED,
    CONIDIAL_RISK_UPDATED,

    PRIMARY_INFECTION_CONDITIONS,
    SECONDARY_SPORULATION_CONDITIONS,
    SECONDARY_INFECTION_CONDITIONS
}